# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# JVM arguments for Gradle daemon - adjust heap size as needed.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin code style: "official" or "obsolete"
kotlin.code.style=official

# Use AndroidX libraries instead of Support Library
android.useAndroidX=true

# Enables Jetifier to migrate third-party libraries to AndroidX
android.enableJetifier=true

# Enables namespacing of R classes for smaller, faster builds
android.nonTransitiveRClass=true
COMET_CHAT_APP_ID=273697874146bc9e
COMET_CHAT_REGION=IN
COMET_CHAT_AUTH_KEY=14e7142bcad5d096a02d29e22c598201b3494082


# Optional: Enable parallel project builds (use cautiously)
# org.gradle.parallel=true
